### ISSUE TITLE
SDK 请求结构问题

### ISSUE THREAD

**Issue by incomingflyingbrick** [alibaba/nls-sdk-java#6]
您好，我正在使用你们的实时语音识别服务，我照着JAVA SDK里面模拟了请求
当我和服务器建立好ws链接之后我给服务器发了以下请求

`{"header":{"namespace":"SpeechTranscriber","name":"StartTranscription","appkey":"H5jgppI3SYX8ouU","task_id":"e03457b95b214d54b74403cc295a27b2","message_id":"ca91f5ad5ad746cca5c0562a73036404","X-NLS-Token":"cc17dc0330ca4fbbaf4a9e0f100a1bae"},"payload":{"format":"pcm","sample_rate":16000,"enable_intermediate_result":true,"enable_punctuation_prediction":false,"enable_inverse_text_normalization":false,"max_sentence_silence":500,"enable_words":false,"enable_ignore_sentence_timeout":false,"disfluency":false,"speech_noise_threshold":0.0,"enable_semantic_sentence_detection":false},"context":{"sdk":"2.1.1","network":{"connect_cost":1000,"upgrade_cost":1000}}}`

然后服务器就断开了，请问这个是什么情况？是不是请求结构哪里不对？
请原谅我没法使用JAVA SDK，因为我用的是C#

**Comment by rockiee281** [comment]
可以发一下服务端给你返回的具体错误信息是什么，在断开链接之前应该会返回相关错误提示
